[tasks.default]
clear = true
command = "echo"
args = ["\n\nDisable default task!\nUsage: cargo make <build/run/clean/image/test>\n\n"]

[tasks.build]
description = "Build all projects"
dependencies = ["build_kernel", "build_loader"]

[tasks.run]
description = "Run rusmikan on qemu"
dependencies = ["build"]
script = '''
tools/run_qemu.sh \
rusmikan-loader/target/x86_64-unknown-uefi/debug/rusmikan-loader.efi \
rusmikan-kernel/target/x86_64-rusmikan/debug/kernel.elf
'''

[tasks.clean]
description = "Remove all artifacts"
dependencies = ["clean_kernel", "clean_loader", "clean_image"]

[tasks.image]
description = "Build image"
dependencies = ["build"]
script = '''
tools/make_image.sh ./target/debug/disk.img /tmp/mnt \
rusmikan-loader/target/x86_64-unknown-uefi/debug/rusmikan-loader.efi \
rusmikan-kernel/target/x86_64-rusmikan/debug/kernel.elf
'''

[tasks.test]
clear = true
# TODO: Add test for loader and rusmikan. Test supports only kernel
description = "Test rusmikan"
dependencies = ["test_kernel"]
script = '''
tools/run_test.sh
'''


# ## Private tasks ##
[tasks.build_kernel]
private = true
description = "Build rusmikan-kernel"
command = "cargo"
args = ["make", "--cwd", "rusmikan-kernel", "build"]

[tasks.build_loader]
private = true
description = "Build rusmikan-loader"
command = "cargo"
args = ["make", "--cwd", "rusmikan-loader", "build"]

[tasks.clean_kernel]
private = true
description = "Remove artifacts in rusmikan-kernel"
command = "cargo"
args = ["make", "--cwd", "rusmikan-kernel", "clean"]

[tasks.clean_loader]
private = true
description = "Remove artifacts in rusmikan-loader"
command = "cargo"
args = ["make", "--cwd", "rusmikan-loader", "clean"]

[tasks.clean_image]
private = true
description = "Remove image file"
command = "rm"
args = ["disk.img"]

[tasks.test_kernel]
private = true
description = "Build test kernel"
command = "cargo"
args = ["make", "--cwd", "rusmikan-kernel", "test"]

